name: Entrega Continua

on:
  workflow_call:

jobs:

  EC2:
    runs-on: ubuntu-latest
    steps:
      # Primeiro, faz o checkout do código para criar a estrutura de pastas do projeto
    - uses: actions/checkout@v3

    - name: Download a Build Artifact
      uses: actions/download-artifact@v4
      with:
      #Arifact name
        name: programa
        path: ./dist
    

    - name: Deploy to Staging server
      uses: easingthemes/ssh-deploy@main
      with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}         
          SOURCE: "dist/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: /home/${{ secrets.REMOTE_USER }}
          EXCLUDE: "postgres-data"


    - name: Execute remote SSH commands
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: bash deploy_script.sh